"""Narratifs d'analyse rédigés à la main, un par indicateur (partie « hybride »).
Expliquent les mouvements historiques réels. La phrase « lecture actuelle » et les
statistiques, elles, sont générées automatiquement (voir stats.py + le rendu).
Marqueur **gras** supporté ; paragraphes séparés par une ligne vide.
"""
NARRATIVES = {
    "bce":
        "La BCE a trois taux qui forment un corridor, mais depuis 2014, avec l'excès de liquidité, "
        "c'est le **taux de dépôt** qui pilote réellement les conditions monétaires de la zone euro.\n\n"
        "**L'ère des taux zéro et négatifs.** Après un pic du refi à 4,25 % en 2008, la BCE glisse "
        "longuement vers le bas. Le dépôt passe carrément en **négatif** : -0,10 % en juin 2014, "
        "-0,40 % en mars 2016 (refi à 0 %), puis **-0,50 % en septembre 2019**. Cause : une inflation "
        "obstinément trop basse et la crise de la dette souveraine.\n\n"
        "**Le resserrement 2022-2023.** En **juillet 2022**, premier relèvement, le dépôt passe de "
        "-0,50 % à 0 (une hausse de 50 points de base d'un coup). S'ensuit le cycle le plus rapide de "
        "l'histoire de la BCE : **dix hausses en quatorze mois**, jusqu'à un pic du dépôt à "
        "**4,00 % en septembre 2023**, pour casser l'inflation post-Covid et le choc énergétique lié "
        "à l'Ukraine.\n\n"
        "**L'assouplissement, puis un revirement.** À partir de **juin 2024**, huit baisses ramènent "
        "le dépôt de 4,00 % à **2,00 % en juin 2025**. Surprise en **juin 2026** : la BCE **remonte** "
        "de 25 points de base (à 2,25 %) sous l'effet de pressions inflationnistes liées au conflit au "
        "Moyen-Orient.\n\n"
        "**Pour le Maroc**, ce que fait la BCE compte doublement : le dirham est arrimé à un panier "
        "où l'euro pèse ~60 %, et BAM ne peut pas trop s'écarter durablement des taux européens sans "
        "conséquences sur le change et les flux de capitaux.",
    "fed":
        "La cible de la Fed est la boussole monétaire mondiale : c'est le taux d'intérêt le plus "
        "suivi de la planète, et ses mouvements se propagent partout.\n\n"
        "**Avant 2022.** Le pic d'avant-crise à **5,25 % (2006-2007)** laisse place à un effondrement "
        "à **0-0,25 % en décembre 2008** (crise financière). Long plancher, puis une normalisation "
        "timide à partir de décembre 2015 (jusqu'à 2,25-2,50 % en 2018), coupée net par le Covid : "
        "retour à zéro en **mars 2020**.\n\n"
        "**Le choc 2022-2023.** Décollage en mars 2022, puis le resserrement **le plus violent depuis "
        "les années 1980**, jusqu'à un pic de **5,25-5,50 % en juillet 2023** (taux effectif 5,33 %), "
        "maintenu treize mois pour briser une inflation à 40 ans de sommet.\n\n"
        "**L'assouplissement 2024-2025.** Six baisses de **septembre 2024** à décembre 2025 (dont une "
        "de 50 points de base pour ouvrir le bal), soit 175 points de base au total, ramènent la "
        "cible à **3,50-3,75 %**. La Fed marque ensuite une pause en 2026, la flambée pétrolière "
        "liée au Moyen-Orient ravivant le risque d'inflation.\n\n"
        "**Pour le Maroc**, les décisions de la Fed débordent via le change (dollar) et les flux de "
        "capitaux, et elles pèsent sur la contrainte externe que BAM doit intégrer.",
    "infl_us":
        "L'inflation américaine en glissement annuel (indice des prix à la consommation). C'est le "
        "thermomètre qui commande le rythme de la Fed, et donc, indirectement, le dollar.\n\n"
        "**La décennie calme.** Tout au long des années 2010, l'inflation US reste sage, autour de "
        "**2 %**, parfois en dessous, sans jamais menacer.\n\n"
        "**L'explosion post-Covid.** À la sortie de la pandémie, elle s'envole jusqu'à un **pic de "
        "9,1 % en juin 2022**, un sommet de quarante ans. Trois moteurs conjugués : une relance "
        "budgétaire massive (chèques aux ménages), des chaînes d'approvisionnement bloquées, et la "
        "flambée de l'énergie liée à l'Ukraine. C'est ce choc qui a déclenché le resserrement "
        "brutal de la Fed.\n\n"
        "**La désinflation.** Reflux marqué vers 3 % courant 2023, puis proche de la cible en "
        "2024-2025, ce qui a permis à la Fed de commencer à baisser. Un risque de résurgence plane "
        "toutefois en 2026 avec la remontée du pétrole.",
    "infl_ze":
        "L'inflation de la zone euro (indice HICP), la variable que la BCE cherche à ancrer autour "
        "de 2 %.\n\n"
        "**Le problème inverse (années 2010).** Longtemps, l'inflation de la zone euro était **trop "
        "basse**, sous la cible et parfois négative, ce qui a justement forcé la BCE aux taux zéro "
        "et négatifs.\n\n"
        "**Le choc énergétique 2022.** Elle bondit à un **pic de 10,6 % en octobre 2022**, du jamais-"
        "vu. Le moteur est très européen : l'envolée du gaz et de l'électricité après l'invasion de "
        "l'Ukraine, l'Europe étant fortement dépendante du gaz russe.\n\n"
        "**La décrue.** Retour vers 2-3 % en 2023-2024, jusqu'à repasser **sous les 2 %** récemment "
        "(l'inflation sous-tire désormais la cible). Cette trajectoire a piloté le calendrier de "
        "baisse des taux de la BCE.\n\n"
        "**Pour le Maroc**, la zone euro est le premier partenaire commercial et la référence du "
        "panier de change du dirham : son inflation et la réponse de la BCE se transmettent "
        "indirectement à la contrainte de BAM.",
    "eurusd":
        "La parité euro-dollar (dollars pour un euro). Elle compte doublement pour le Maroc : le "
        "dirham est arrimé à un panier **~60 % euro / 40 % dollar**, et le pétrole se facture en "
        "dollars.\n\n"
        "**Le grand affaiblissement de l'euro.** Autour de **1,60 à la mi-2008**, l'euro s'érode "
        "ensuite. Le programme de rachats d'actifs de la BCE (2015) le ramène vers 1,05-1,10.\n\n"
        "**Sous la parité (2022).** En **septembre 2022**, l'euro passe **sous la parité** (plancher "
        "à 0,95), une première en une vingtaine d'années. Cause : les hausses agressives de la Fed "
        "face à une BCE en retard, et le choc énergétique qui menace la croissance européenne.\n\n"
        "**Rebond puis rechute.** Remontée vers **1,11 en septembre 2024**, avant une rechute après "
        "l'élection américaine de novembre 2024 (autour de 1,01), la menace tarifaire ravivant le "
        "dollar.\n\n"
        "**Pour le Maroc**, un dollar fort renchérit la facture pétrolière **même à baril inchangé** : "
        "c'est le multiplicateur de l'inflation importée. À croiser systématiquement avec le Brent.",
    "brent":
        "Le prix du baril de Brent, référence de la facture pétrolière marocaine (importée depuis "
        "l'Europe et la Méditerranée). C'est un canal majeur d'inflation subie, que la politique "
        "monétaire ne contrôle pas.\n\n"
        "**Les grands cycles.** Pic historique à **~147 $ en juillet 2008**, puis crash à ~40 $ fin "
        "2008 (récession mondiale). Plateau haut ~110 $ de 2011 à 2014, avant l'effondrement à "
        "**~30 $ début 2016** sous l'afflux de pétrole de schiste américain.\n\n"
        "**Covid et Ukraine.** Autour de 70 $ en 2018-2019, puis le crash de **~20 $ en avril 2020** "
        "(demande évaporée par les confinements). Rebond violent ensuite jusqu'à **~120 $ à la mi-"
        "2022** avec l'invasion de l'Ukraine.\n\n"
        "**Depuis.** Reflux progressif : ~80 $ en 2023, moyenne ~80 $ en 2024, ~65-70 $ en 2025, et "
        "bas-60 $ début 2026, avec un risque de flambée sur les tensions au Moyen-Orient.\n\n"
        "**Pour le Maroc**, importateur net d'énergie, chaque hausse se transmet à l'inflation via le "
        "carburant, le transport et les engrais. À lire toujours avec l'USD/MAD : un dollar fort et "
        "un baril cher, c'est la double peine.",
    "food":
        "L'indice FMI des prix alimentaires mondiaux. Le Maroc importe une part de son blé, de ses "
        "huiles et de son sucre : cet indice est donc un intrant direct de l'inflation alimentaire "
        "locale.\n\n"
        "**Les flambées historiques.** L'indice bondit en **2008** puis en **2011**, deux épisodes "
        "de prix alimentaires records qui ont nourri des tensions sociales (les émeutes de la faim, "
        "et en partie le Printemps arabe).\n\n"
        "**Le record de 2022.** L'invasion de l'Ukraine, l'un des greniers à blé de la planète, "
        "propulse l'indice à un **sommet historique début 2022**. Reflux depuis, mais le niveau "
        "reste élevé par rapport à la décennie précédente.\n\n"
        "**Pour le Maroc**, comme l'alimentaire pèse très lourd dans le panier, ces flambées "
        "expliquent pourquoi l'inflation globale peut s'envoler alors que la sous-jacente reste "
        "sage : le choc vient de l'assiette, pas de la demande interne.",
    "gepu":
        "L'indice mondial d'incertitude de politique économique (GEPU), construit à partir de la "
        "fréquence de termes liés à l'incertitude dans la presse de dizaines de pays.\n\n"
        "**Chaque grand choc laisse un pic.** Crise financière de 2008, crise de la dette de la zone "
        "euro (2011-2012), **Brexit (juin 2016)**, guerre commerciale entre les États-Unis et la "
        "Chine (2018-2019).\n\n"
        "**Les records récents.** Le **Covid en 2020** fait exploser l'indice à un niveau sans "
        "précédent, puis l'invasion de l'Ukraine (2022) et, plus récemment, les tensions tarifaires "
        "et géopolitiques au Moyen-Orient (2025-2026) le maintiennent élevé.\n\n"
        "**Pour le Maroc**, c'est un proxy chiffré du critère **« incertitude internationale »** que "
        "BAM cite dans presque chaque communiqué et qu'aucune règle mécanique ne capture. La logique "
        "est nette : plus l'incertitude est forte, plus le Conseil penche pour le statu quo, "
        "c'est-à-dire attendre plutôt qu'agir.",
    "monia":
        "MONIA (Moroccan Overnight Index Average) est le taux auquel les banques marocaines se "
        "prêtent entre elles au jour le jour. Sa règle de vie est simple : il reste **collé au taux "
        "directeur de Bank Al-Maghrib**. Ses grands mouvements ne sont donc pas du hasard, ce sont "
        "les décisions du Conseil.\n\n"
        "**La détente Covid (2020).** BAM abaisse le directeur de 2,25 % à **2,00 % en mars 2020**, "
        "puis à **1,50 % en juin 2020** (une coupe de 50 points de base, exceptionnelle). MONIA "
        "plonge avec, jusqu'aux alentours de 1,4 %.\n\n"
        "**Le plateau 2021.** Statu quo à 1,50 %, MONIA reste plat : l'inflation d'alors est jugée "
        "surtout importée et temporaire.\n\n"
        "**Le resserrement 2022-2023.** Face à l'inflation, BAM remonte le directeur pour la première "
        "fois depuis 2008 : de 1,50 % à **2,00 % en septembre 2022**, **2,50 % en décembre 2022**, "
        "puis **3,00 % en mars 2023**. MONIA suit chaque marche et culmine autour de 3 %.\n\n"
        "**L'assouplissement 2024-2025.** L'inflation retombée, BAM enclenche des baisses : à partir "
        "de **septembre 2024**, trois coupes de 25 points de base ramènent le directeur de 3,00 % à "
        "**2,25 % en mars 2025**, niveau tenu depuis. MONIA redescend vers 2,2 %.\n\n"
        "**Le reste du temps**, MONIA ne bouge que de quelques points de base. Ses petits écarts au "
        "directeur sont le vrai signal à surveiller : ils trahissent des tensions de liquidité dans "
        "le système bancaire (déficit structurel que BAM comble par ses injections).",
    "inflation":
        "L'inflation marocaine se lit sur deux courbes : l'inflation **globale** (tout le panier) et "
        "l'inflation **sous-jacente** (core), qui retire les produits volatils (alimentaire frais, "
        "énergie, prix administrés) pour montrer la tendance de fond. Au Maroc, l'alimentaire pèse "
        "très lourd dans le panier, ce qui rend la globale bien plus nerveuse que la core.\n\n"
        "**Avant 2022**, l'inflation était faible et calme, souvent entre 0 et 2 %, avec des mois "
        "proches de zéro voire négatifs. La core restait remarquablement stable, signe d'une demande "
        "interne sans surchauffe.\n\n"
        "**Le choc 2022-2023.** La globale s'envole à **+6,6 % en moyenne en 2022**, puis atteint un "
        "**pic de 10,1 % en février 2023**, du jamais-vu depuis les années 1990. Le moteur est "
        "importé : flambée du blé et de l'énergie après l'invasion de l'Ukraine, doublée d'une "
        "sécheresse locale qui renchérit les produits frais. La core grimpe elle aussi, jusqu'à "
        "**5,9 % en 2023** : le choc, au départ alimentaire, s'était partiellement diffusé au reste "
        "des prix.\n\n"
        "**La désinflation 2024-2025.** Le reflux est brutal : la globale retombe à **+0,9 % en 2024** "
        "puis **+0,8 % en 2025**, et la core redescend à **+2,4 % en 2024**. Attention au piège : "
        "désinflation n'est pas déflation. Les prix ne baissent pas, ils montent seulement moins "
        "vite ; le niveau atteint en 2022-2023 reste en place, donc le pouvoir d'achat ne se "
        "reconstitue pas.\n\n"
        "**Pour BAM**, l'écart entre globale et core a servi à jauger la part temporaire du choc ; "
        "c'est la core, la tendance de fond, que le Conseil cherche à ramener vers 2 %. Son reflux a "
        "ouvert la voie au cycle de baisse des taux entamé en septembre 2024.",
    "pib":
        "La croissance du PIB réel en glissement annuel mesure le rythme de l'économie marocaine. Sa "
        "particularité : une forte dépendance à l'**agriculture**, elle-même dépendante de la "
        "**pluie**. Une bonne campagne gonfle la croissance, une sécheresse la plombe, "
        "indépendamment de la santé du reste de l'économie.\n\n"
        "**Avant 2020**, la croissance oscille autour de **3 à 4 %**, mais en dents de scie au gré "
        "des campagnes céréalières.\n\n"
        "**Le choc Covid (2020-2021).** Le confinement provoque un effondrement historique, jusqu'à "
        "**environ -14 % au 2e trimestre 2020**. Un an plus tard, l'économie rebondit mécaniquement "
        "à **environ +14 % au 2e trimestre 2021**, par simple effet de base (on compare à un point "
        "très bas). Ce grand V domine visuellement la courbe.\n\n"
        "**Depuis 2022**, retour à une croissance plus ordinaire, autour de **3 %**, mais bridée par "
        "des **sécheresses répétées** qui pèsent sur la valeur ajoutée agricole. Le non-agricole, "
        "lui, est plus stable.\n\n"
        "**Pour lire l'activité**, c'est le **PIB non-agricole** qu'il faut regarder : il reflète la "
        "vraie dynamique de la demande interne, celle qui crée des pressions inflationnistes, alors "
        "que la partie agricole n'est que du bruit météo pour la politique monétaire.",
    "output_gap":
        "L'écart de production (output gap) mesure la distance entre le PIB observé et le PIB "
        "potentiel, c'est-à-dire la production soutenable sans dérapage des prix. C'est un input "
        "central de BAM, reconstruit ici par ses **trois méthodes** : filtre HP (statistique), "
        "fonction de production (structurelle : capital, travail, productivité) et modèle semi-"
        "structurel (qui cale le gap sur l'inflation et le chômage). C'est la méthodologie du "
        "document de travail de BAM (Chafik, 2017), avec ses paramètres estimés.\n\n"
        "**Comment le lire.** À prendre comme un faisceau, jamais comme une mesure au point près : ce "
        "qui compte, c'est le **signe** (positif = surchauffe et pression sur les prix ; négatif = "
        "mou) et la **convergence** des trois courbes. Quand elles pointent dans la même direction, "
        "on peut s'y fier.\n\n"
        "**Le grand creux Covid.** Le gap plonge nettement en négatif en 2020 (l'économie tourne "
        "très en dessous de son potentiel pendant les confinements), avant de se refermer avec le "
        "rebond.\n\n"
        "**Le piège de fin d'échantillon.** Les tout derniers points sont les moins fiables : le "
        "filtre se cale sur les observations récentes, et le gap y est fortement révisé à mesure que "
        "de nouvelles données arrivent. Or c'est justement le point présent qui compte pour "
        "anticiper la prochaine décision. C'est la limite même de l'outil, à assumer.",
    "output_gap_q":
        "La version **trimestrielle** de l'output gap, obtenue par un simple filtre HP sur le PIB "
        "réel trimestriel. Elle est plus réactive que le trio annuel, donc plus utile pour anticiper "
        "une décision trimestrielle de BAM.\n\n"
        "**Ses mouvements** suivent le cycle : un creux marqué pendant le Covid (2020), un rebond, "
        "puis des oscillations autour de zéro au fil des trimestres.\n\n"
        "**Sa fragilité.** Comme toute estimation HP, elle souffre du biais de fin d'échantillon : "
        "les derniers trimestres sont **fortement révisés** quand de nouvelles données arrivent. À "
        "utiliser comme un signal de direction, jamais comme une mesure exacte.",
    "ipai":
        "L'indice des prix des actifs immobiliers (base 100 au premier trimestre 2006), publié par "
        "l'ANCFCC avec Bank Al-Maghrib. Deux courbes : le global et le résidentiel.\n\n"
        "**Le fait marquant : la stagnation.** Sur près de vingt ans, l'indice n'a **quasiment pas "
        "bougé en nominal**, oscillant entre ~100 et ~114. Autrement dit, corrigés de l'inflation, "
        "les prix immobiliers marocains ont **baissé en termes réels**.\n\n"
        "**Ni bulle, ni krach.** Contrairement à beaucoup de pays, le Maroc n'a connu ni flambée ni "
        "effondrement immobilier ; le marché est resté remarquablement plat, avec seulement de "
        "légères ondulations (petit repli après 2008, stabilité ensuite).\n\n"
        "**Pour la politique monétaire**, la conséquence est nette : le canal de l'effet de richesse "
        "immobilier joue faiblement au Maroc, puisque le patrimoine immobilier ne s'apprécie guère.",
    "m3":
        "Les agrégats monétaires mesurent la quantité de monnaie en circulation, classés par "
        "liquidité décroissante : **M1** (billets et dépôts à vue), **M2** (M1 plus l'épargne à vue) "
        "et **M3** (M2 plus les autres actifs monétaires), l'agrégat large le plus suivi.\n\n"
        "**Une progression continue.** M3 est passé d'environ 700 milliards de dirhams au milieu des "
        "années 2000 à plus de **2 000 milliards** aujourd'hui, une croissance régulière qui "
        "accompagne l'expansion de l'économie et du crédit.\n\n"
        "**Pourquoi BAM le surveille.** En théorie monétaire, une croissance excessive de M3 précède "
        "l'inflation à moyen terme (trop de monnaie pour trop peu de biens). C'est donc un signal de "
        "fond, à mettre en regard de la croissance du crédit.\n\n"
        "**Limite.** Donnée annuelle, donc lente : utile comme contexte structurel, pas pour un "
        "timing fin de décision.",
    "capi":
        "La capitalisation boursière totale de la Bourse de Casablanca, c'est-à-dire la valeur de "
        "marché de toutes les actions cotées (l'indice MASI en est le reflet).\n\n"
        "**Ce qu'elle reflète.** L'appétit pour le risque et la valorisation des entreprises cotées ; "
        "elle alimente en théorie un canal d'effet de richesse (quand la Bourse monte, les "
        "détenteurs se sentent plus riches et consomment davantage).\n\n"
        "**Un marché étroit.** La cote marocaine reste **petite et concentrée** : une poignée de "
        "secteurs (banques, télécoms, immobilier) domine la capitalisation, avec un flottant limité "
        "et une liquidité modeste.\n\n"
        "**Pour la politique monétaire**, ce canal d'effet de richesse joue donc **moins qu'ailleurs** : "
        "la Bourse ne touche qu'une fraction restreinte des ménages. Donnée annuelle.",
    "depots":
        "Le taux moyen pondéré des dépôts à terme (comptes et bons de caisse) à 6 et 12 mois, "
        "c'est-à-dire le taux **créditeur** que les banques servent à l'épargne bloquée. C'est le "
        "miroir passif du crédit : ce que la banque paie pour se financer auprès des déposants.\n\n"
        "**Ce qu'il mesure.** La transmission de la politique monétaire au passif bancaire. Quand BAM "
        "baisse son taux directeur, le coût de la liquidité recule et les banques rémunèrent moins "
        "l'épargne ; quand elle le monte, la concurrence pour les dépôts fait remonter ces taux. La "
        "réaction est **lente et incomplète** : les banques ajustent avec retard et lissent, car un "
        "dépôt à terme est un contrat de plusieurs mois.\n\n"
        "**La grande désinflation des taux (2013-2020).** Le fait dominant du graphe est la longue "
        "descente. Début 2014, le 12 mois dépassait **4 %** et le 6 mois frôlait 3,7 %. BAM a abaissé "
        "son taux directeur de 3 % à 2,5 % (2014), puis 2,25 % (2016), et les taux créditeurs ont "
        "suivi marche après marche : autour de **3 %** en 2016-2017, puis sous 3 % dès 2018. Chaque "
        "palier BAM se lit dans la pente, avec quelques mois de décalage.\n\n"
        "**Le choc Covid (2020).** Face à la crise, BAM a coupé son taux directeur à 2 % puis **1,5 %** "
        "en juin 2020, un plus bas historique. Les dépôts à terme ont glissé vers la zone **2 % à "
        "2,7 %**, leur plancher de la décennie : l'épargne bloquée ne rapportait presque plus rien en "
        "termes réels une fois l'inflation déduite.\n\n"
        "**Le resserrement anti-inflation (2022-2023), puis la détente (2024-2025).** Quand "
        "l'inflation a bondi, BAM a remonté son taux directeur de 1,5 % à 2 % (sept. 2022), 2,5 % "
        "(déc. 2022) puis **3 %** (mars 2023). La remontée des taux créditeurs a été **timide** : le "
        "système bancaire marocain était en surliquidité relative, les banques n'avaient pas un besoin "
        "pressant de courir après les dépôts, donc elles ont peu relevé la rémunération. Depuis les "
        "baisses de 2024-2025 (retour vers 2,25 %), les taux oscillent sans tendance nette autour de "
        "**2,2 % à 2,8 %**.\n\n"
        "**Attention à la lecture mensuelle.** Ce sont des **moyennes pondérées de la production du "
        "mois** : d'un mois à l'autre, la composition des nouveaux dépôts (gros clients "
        "institutionnels vs particuliers, banques agressives ou non) fait sauter le chiffre de "
        "plusieurs dizaines de points de base sans que la politique monétaire ait bougé. Il faut lire "
        "la **tendance sur plusieurs mois**, pas le point isolé. Le 12 mois est en général au-dessus "
        "du 6 mois (prime de terme), mais l'écart est étroit et s'inverse ponctuellement.\n\n"
        "**Pour anticiper BAM**, ces taux sont un indicateur de transmission plus qu'un déclencheur : "
        "ils confirment, avec retard, qu'une décision passée s'est bien propagée à l'économie. Une "
        "transmission faible (taux qui bougent peu après un mouvement directeur) signale que le canal "
        "bancaire est engourdi, ce qui pèse dans le diagnostic de BAM sur l'efficacité de sa politique.",
    "debiteurs":
        "Les taux débiteurs, c'est-à-dire le taux d'intérêt que les banques **facturent sur les "
        "nouveaux crédits**, mesurés par l'enquête trimestrielle de BAM. C'est le maillon central de "
        "la transmission : la politique monétaire ne mord sur l'économie réelle que si une baisse du "
        "taux directeur se répercute effectivement sur le coût du crédit aux entreprises et aux "
        "ménages.\n\n"
        "**La hiérarchie des taux.** Le graphe montre bien la logique du risque. Le crédit à la "
        "**consommation** est le plus cher (autour de **7 %**, non garanti, emprunteurs individuels), "
        "l'**équipement** le moins cher (5 % à 6 %, investissement des entreprises, souvent adossé à "
        "des garanties et objet d'une forte concurrence entre banques). Trésorerie, immobilier et taux "
        "global se tiennent entre les deux. Cet ordre est stable dans le temps.\n\n"
        "**La grande détente (2010-2016).** Le mouvement dominant est une **baisse continue**. Le taux "
        "global part de **6,49 %** début 2010 pour toucher un plancher autour de **5,1 %** en 2016. "
        "Cette descente colle aux baisses du taux directeur BAM sur la période : de 3,25 % il passe à "
        "3 % (2012), 2,75 % puis 2,5 % (2014) et 2,25 % (2016). La transmission fonctionne, mais de "
        "façon **amortie** : le directeur perd 1 point (de 3,25 % à 2,25 %) tandis que le taux global "
        "aux emprunteurs ne recule que d'environ 1,4 point, l'écart de marge bancaire restant large.\n\n"
        "**Le léger rebond de 2017.** Après le point bas de 2016, les taux remontent doucement en 2017 "
        "(taux global à **5,77 %** fin d'année) alors même que le directeur ne bouge pas. Signe que le "
        "coût du crédit ne dépend pas que de BAM : concurrence, perception du risque et conditions de "
        "liquidité jouent aussi.\n\n"
        "**Le plancher Covid (2018-2021).** La série continue de descendre : de ~5,1 % en 2018 elle "
        "tombe à son point bas autour de **4,3 % à 4,4 %** en 2020-2021, quand BAM coupe son taux "
        "directeur à 2 % puis **1,5 %** (juin 2020) pour amortir le choc pandémique. Le crédit "
        "n'avait jamais été aussi bon marché.\n\n"
        "**Le sursaut anti-inflation (2022-2023).** Fin 2022 le taux global est encore à 4,50 %, mais "
        "quand BAM remonte son directeur de 1,5 % à 2 % (sept. 2022), 2,5 % (déc. 2022) puis **3 %** "
        "(mars 2023), les taux débiteurs grimpent nettement, trimestre après trimestre : 5,03 % au "
        "T1 2023, 5,26 % au T2, puis **5,36 %** aux T3-T4, soit près de **0,9 point** de hausse en un "
        "an. C'est la transmission la plus rapide et la plus nette de tout l'historique, signe qu'un "
        "resserrement passe plus vite qu'un assouplissement.\n\n"
        "**La détente récente (2024-2026).** À mesure que BAM redescend son taux (2,75 % en 2024, "
        "2,25 % en 2025), le taux global reflue jusqu'à **4,81 %** au T2 2026. Le crédit à la "
        "**consommation** reste structurellement le plus cher (autour de 6,8 % à 7 %), l'équipement et "
        "l'immobilier les moins chers.\n\n"
        "**Pourquoi c'est décisif pour BAM.** Ces taux répondent directement à la question que se pose "
        "le Conseil : ma politique atteint-elle vraiment l'économie ? Une baisse du directeur qui ne "
        "fait pas descendre les taux débiteurs est une politique **inefficace**, et peut justifier "
        "d'aller plus loin. C'est aussi ici que se lisent les tensions sur l'offre de crédit, à "
        "croiser avec l'enquête sur les conditions d'octroi.\n\n"
        "**Sur la construction.** La série assemble plusieurs exports trimestriels de BAM et couvre "
        "désormais **2010 à 2026 sans interruption** (66 trimestres). Elle est directement exploitable "
        "en modélisation comme mesure du coût effectif du crédit et de la vitesse de transmission.",
    "icm":
        "L'Indice de Confiance des Ménages (ICM), publié chaque trimestre par le HCP à partir de son "
        "enquête nationale de conjoncture. C'est un **indice de sentiment** : la moyenne des soldes "
        "d'opinion des ménages sur sept questions (évolution passée et future du niveau de vie, "
        "finances personnelles, chômage attendu, opportunité de faire des achats importants).\n\n"
        "**Comment le lire.** L'échelle va de 0 à 200, avec **100 comme point neutre**. Fait "
        "marquant : sur tout l'historique depuis 2008, l'ICM marocain **n'a jamais atteint 100**. Les "
        "ménages sont donc structurellement pessimistes ; ce qui compte n'est pas le niveau absolu "
        "mais sa **direction** et son ampleur.\n\n"
        "**Le plateau (2008-2019).** Pendant une décennie, l'indice oscille dans une bande **75 à 87**, "
        "sans tendance forte. Il touche même son plus haut de la série début 2018 (**87,3**). Le moral "
        "est bas dans l'absolu, mais stable.\n\n"
        "**Le choc Covid (2020).** L'ICM décroche : de près de 78 fin 2019, il tombe autour de **65** "
        "au 2e trimestre 2020, quand le confinement frappe l'emploi et les revenus.\n\n"
        "**L'effondrement inflationniste (2022-2023).** C'est le mouvement le plus violent du graphe. "
        "La flambée des prix alimentaires et de l'énergie écrase le pouvoir d'achat, et l'indice "
        "plonge jusqu'à son **plus bas historique de 44,3** au 4e trimestre 2023. Les ménages n'ont "
        "jamais été aussi sombres depuis le début de la mesure.\n\n"
        "**Le rebond (2025-2026).** À mesure que l'inflation reflue et que BAM assouplit, la confiance "
        "se redresse nettement : de 54,6 (T2 2025) elle remonte à **64,4** au 1er trimestre 2026, avant "
        "de refluer à 60,1 au T2. Un rebond réel, mais toujours loin sous 100.\n\n"
        "**Pour anticiper BAM.** L'ICM est un thermomètre de la **demande intérieure**. Une confiance "
        "déprimée signale une consommation molle, donc des pressions inflationnistes faibles côté "
        "demande, ce qui plaide pour une politique accommodante ; un rebond marqué peut au contraire "
        "annoncer une reprise de la consommation. C'est un signal **avancé et qualitatif** : utile "
        "comme confirmation du diagnostic sur le cycle, à croiser avec la croissance du PIB et le "
        "crédit, mais trop bruité pour être un déclencheur mécanique de décision.",
}
