"""English translations of the hand-written analysis narratives in narratives.py.
Same keys, same structure (paragraphs separated by a blank line, **bold** supported).
"""
NARRATIVES_EN = {
    "bce":
        "The ECB runs three rates that form a corridor, but since 2014, with excess liquidity in the "
        "system, it is the **deposit rate** that actually drives euro-area monetary conditions.\n\n"
        "**The zero and negative rate era.** After the refi rate peaked at 4.25% in 2008, the ECB "
        "eased steadily. The deposit rate went outright **negative**: -0.10% in June 2014, -0.40% in "
        "March 2016 (refi at 0%), then **-0.50% in September 2019**. Cause: stubbornly low inflation "
        "and the sovereign debt crisis.\n\n"
        "**The 2022-2023 tightening.** In **July 2022**, the first hike lifted the deposit rate from "
        "-0.50% to 0% (a 50bp move at once). What followed was the fastest tightening cycle in ECB "
        "history: **ten hikes in fourteen months**, up to a deposit-rate peak of **4.00% in September "
        "2023**, aimed at breaking post-Covid inflation and the Ukraine-linked energy shock.\n\n"
        "**Easing, then a reversal.** From **June 2024**, eight cuts brought the deposit rate down from "
        "4.00% to **2.00% in June 2025**. A surprise in **June 2026**: the ECB **hiked** 25bp (to "
        "2.25%) as inflation pressures resurfaced from the Middle East conflict.\n\n"
        "**For Morocco**, what the ECB does matters twice over: the dirham is pegged to a basket in "
        "which the euro weighs ~60%, and BAM cannot diverge too far or too long from European rates "
        "without consequences for the exchange rate and capital flows.",
    "fed":
        "The Fed's target rate is the world's monetary compass: the most closely watched interest rate "
        "on the planet, and its moves ripple everywhere.\n\n"
        "**Before 2022.** The pre-crisis peak of **5.25% (2006-2007)** gave way to a collapse to "
        "**0-0.25% in December 2008** (financial crisis). A long floor, then a timid normalization "
        "from December 2015 (up to 2.25-2.50% in 2018), cut short by Covid: back to zero in **March "
        "2020**.\n\n"
        "**The 2022-2023 shock.** Liftoff in March 2022, then the **sharpest tightening since the "
        "1980s**, up to a peak of **5.25-5.50% in July 2023** (effective rate 5.33%), held for thirteen "
        "months to break 40-year-high inflation.\n\n"
        "**The 2024-2025 easing.** Six cuts from **September 2024** to December 2025 (starting with a "
        "50bp move), 175bp in total, brought the target down to **3.50-3.75%**. The Fed then paused in "
        "2026 as the Middle East oil spike revived inflation risk.\n\n"
        "**For Morocco**, Fed decisions spill over through the exchange rate (the dollar) and capital "
        "flows, and they weigh on the external constraint BAM has to factor in.",
    "infl_us":
        "US inflation, year-on-year (consumer price index). This is the gauge that sets the Fed's "
        "pace, and therefore, indirectly, the dollar.\n\n"
        "**The quiet decade.** Throughout the 2010s, US inflation stayed tame, around **2%**, "
        "sometimes below, never threatening.\n\n"
        "**The post-Covid surge.** Coming out of the pandemic, it shot up to a **peak of 9.1% in June "
        "2022**, a 40-year high. Three forces combined: massive fiscal stimulus (stimulus checks), "
        "clogged supply chains, and the energy spike from the Ukraine war. This is the shock that "
        "triggered the Fed's brutal tightening.\n\n"
        "**Disinflation.** A sharp pullback toward 3% during 2023, then close to target in 2024-2025, "
        "which let the Fed start cutting. A resurgence risk looms in 2026 as oil prices climb again.",
    "infl_ze":
        "Euro-area inflation (HICP), the variable the ECB tries to anchor around 2%.\n\n"
        "**The opposite problem (2010s).** For a long stretch, euro-area inflation was **too low**, "
        "below target and sometimes negative, which is precisely what forced the ECB into zero and "
        "negative rates.\n\n"
        "**The 2022 energy shock.** It jumped to a **peak of 10.6% in October 2022**, unprecedented. "
        "The driver was distinctly European: the surge in gas and electricity prices after the "
        "invasion of Ukraine, given Europe's heavy reliance on Russian gas.\n\n"
        "**The pullback.** Back to 2-3% in 2023-2024, and recently even **below 2%** (inflation now "
        "undershoots target). This trajectory drove the ECB's rate-cutting calendar.\n\n"
        "**For Morocco**, the euro area is the top trading partner and the reference for the dirham's "
        "currency basket: its inflation and the ECB's response feed indirectly into BAM's constraint.",
    "eurusd":
        "The euro-dollar exchange rate (dollars per euro). It matters twice over for Morocco: the "
        "dirham is pegged to a basket that is **~60% euro / 40% dollar**, and oil is priced in "
        "dollars.\n\n"
        "**The great euro weakening.** Around **1.60 in mid-2008**, the euro then eroded. The ECB's "
        "asset-purchase programme (2015) pulled it toward 1.05-1.10.\n\n"
        "**Below parity (2022).** In **September 2022**, the euro fell **below parity** (a low of "
        "0.95), a first in about twenty years. Cause: the Fed's aggressive hikes against a lagging "
        "ECB, plus the energy shock threatening European growth.\n\n"
        "**Rebound, then relapse.** A climb back to **1.11 in September 2024**, before a relapse after "
        "the US election in November 2024 (around 1.01), as tariff threats revived the dollar.\n\n"
        "**For Morocco**, a strong dollar raises the oil bill **even with an unchanged barrel price**: "
        "it is the multiplier of imported inflation. Always read it alongside Brent.",
    "brent":
        "The Brent crude price, the reference for Morocco's oil bill (imported from Europe and the "
        "Mediterranean). It is a major channel of imported inflation that monetary policy does not "
        "control.\n\n"
        "**The big cycles.** A historic peak of **~$147 in July 2008**, then a crash to ~$40 by late "
        "2008 (global recession). A high plateau of ~$110 from 2011 to 2014, before collapsing to "
        "**~$30 in early 2016** as US shale oil flooded the market.\n\n"
        "**Covid and Ukraine.** Around $70 in 2018-2019, then the crash to **~$20 in April 2020** "
        "(demand evaporated under lockdowns). A sharp rebound followed, up to **~$120 in mid-2022** "
        "with the invasion of Ukraine.\n\n"
        "**Since then.** A gradual pullback: ~$80 in 2023, ~$80 average in 2024, ~$65-70 in 2025, and "
        "low-$60s in early 2026, with a flare-up risk from Middle East tensions.\n\n"
        "**For Morocco**, a net energy importer, every rise feeds through to inflation via fuel, "
        "transport and fertilizers. Always read alongside USD/MAD: a strong dollar and an expensive "
        "barrel is a double blow.",
    "food":
        "The IMF's global food price index. Morocco imports a share of its wheat, oils and sugar, so "
        "this index is a direct input into local food inflation.\n\n"
        "**Historic spikes.** The index jumped in **2008** and again in **2011**, two episodes of "
        "record food prices that fed social tension (food riots, and partly the Arab Spring).\n\n"
        "**The 2022 record.** The invasion of Ukraine, one of the world's breadbaskets, pushed the "
        "index to a **historic peak in early 2022**. It has eased since, but the level remains high "
        "compared with the previous decade.\n\n"
        "**For Morocco**, since food carries heavy weight in the basket, these spikes explain why "
        "headline inflation can surge while core stays subdued: the shock comes from the plate, not "
        "from domestic demand.",
    "gepu":
        "The Global Economic Policy Uncertainty (GEPU) index, built from the frequency of "
        "uncertainty-related terms in the press across dozens of countries.\n\n"
        "**Every major shock leaves a spike.** The 2008 financial crisis, the euro-area debt crisis "
        "(2011-2012), **Brexit (June 2016)**, the US-China trade war (2018-2019).\n\n"
        "**Recent records.** **Covid in 2020** blew the index to an unprecedented level, then the "
        "invasion of Ukraine (2022) and, more recently, tariff and geopolitical tensions in the "
        "Middle East (2025-2026) keep it elevated.\n\n"
        "**For Morocco**, this is a quantified proxy for the **\"international uncertainty\"** "
        "criterion BAM cites in nearly every statement, one that no mechanical rule captures. The "
        "logic is clear: the higher the uncertainty, the more the Council leans toward the status quo, "
        "i.e. waiting rather than acting.",
    "monia":
        "MONIA (Moroccan Overnight Index Average) is the rate at which Moroccan banks lend to each "
        "other overnight. Its rule of life is simple: it stays **glued to Bank Al-Maghrib's key "
        "rate**. Its big moves are therefore not random, they are the Council's decisions.\n\n"
        "**The Covid easing (2020).** BAM cut the key rate from 2.25% to **2.00% in March 2020**, "
        "then to **1.50% in June 2020** (an unusual 50bp cut). MONIA fell along with it, to around "
        "1.4%.\n\n"
        "**The 2021 plateau.** Status quo at 1.50%, MONIA stayed flat: inflation at the time was seen "
        "as mostly imported and temporary.\n\n"
        "**The 2022-2023 tightening.** Facing inflation, BAM raised the key rate for the first time "
        "since 2008: from 1.50% to **2.00% in September 2022**, **2.50% in December 2022**, then "
        "**3.00% in March 2023**. MONIA tracked every step and peaked around 3%.\n\n"
        "**The 2024-2025 easing.** With inflation back down, BAM started cutting: from **September "
        "2024**, three 25bp cuts brought the key rate from 3.00% to **2.25% in March 2025**, a level "
        "held since. MONIA eased back toward 2.2%.\n\n"
        "**The rest of the time**, MONIA only moves by a few basis points. Its small gaps to the key "
        "rate are the real signal to watch: they betray liquidity tensions in the banking system (a "
        "structural deficit that BAM fills through its injections).",
    "inflation":
        "Moroccan inflation reads on two curves: **headline** inflation (the full basket) and "
        "**core** (underlying) inflation, which strips out volatile items (fresh food, energy, "
        "administered prices) to show the underlying trend. In Morocco, food carries heavy weight in "
        "the basket, which makes headline far more volatile than core.\n\n"
        "**Before 2022**, inflation was low and calm, often between 0 and 2%, with some months near "
        "zero or even negative. Core stayed remarkably stable, a sign of demand with no overheating.\n\n"
        "**The 2022-2023 shock.** Headline surged to **+6.6% on average in 2022**, then hit a **peak "
        "of 10.1% in February 2023**, unseen since the 1990s. The driver was imported: a wheat and "
        "energy spike after the invasion of Ukraine, compounded by a local drought that pushed up "
        "fresh produce prices. Core climbed too, up to **5.9% in 2023**: a shock that started in food "
        "had partly spread to the rest of prices.\n\n"
        "**The 2024-2025 disinflation.** The pullback was sharp: headline fell to **+0.9% in 2024** "
        "then **+0.8% in 2025**, and core eased to **+2.4% in 2024**. Mind the trap: disinflation is "
        "not deflation. Prices are not falling, they are just rising more slowly; the level reached in "
        "2022-2023 stays in place, so purchasing power does not recover.\n\n"
        "**For BAM**, the gap between headline and core was used to gauge how much of the shock was "
        "temporary; it is core, the underlying trend, that the Council seeks to bring back toward 2%. "
        "Its pullback opened the door to the rate-cutting cycle that began in September 2024.",
    "pib":
        "Real GDP growth, year-on-year, measures the pace of the Moroccan economy. Its defining "
        "feature: heavy dependence on **agriculture**, itself dependent on **rainfall**. A good season "
        "inflates growth, a drought crushes it, regardless of how the rest of the economy is doing.\n\n"
        "**Before 2020**, growth oscillated around **3 to 4%**, but in a sawtooth pattern driven by "
        "cereal harvests.\n\n"
        "**The Covid shock (2020-2021).** The lockdown caused a historic collapse, down to roughly "
        "**-14% in Q2 2020**. A year later, the economy mechanically bounced to roughly **+14% in Q2 "
        "2021**, purely a base effect (comparing against a very low point). This big V dominates the "
        "chart visually.\n\n"
        "**Since 2022**, a return to more ordinary growth, around **3%**, but capped by **repeated "
        "droughts** that weigh on agricultural value added. Non-agricultural activity is more stable.\n\n"
        "**To read activity**, look at **non-agricultural GDP**: it reflects the real dynamics of "
        "domestic demand, the one that creates inflationary pressure, while the agricultural share is "
        "just weather noise for monetary policy.",
    "output_gap":
        "The output gap measures the distance between observed and potential GDP, i.e. the level of "
        "production sustainable without price slippage. It is a central input for BAM, reconstructed "
        "here through its **three methods**: the HP filter (statistical), the production function "
        "(structural: capital, labour, productivity) and a semi-structural model (which anchors the "
        "gap to inflation and unemployment). This follows the methodology of BAM's working paper "
        "(Chafik, 2017), with its estimated parameters.\n\n"
        "**How to read it.** Treat it as a bundle, never as a precise point estimate: what matters is "
        "the **sign** (positive = overheating and upward price pressure; negative = slack) and the "
        "**convergence** of the three curves. When they point the same way, you can trust the "
        "reading.\n\n"
        "**The big Covid dip.** The gap plunges sharply negative in 2020 (the economy runs well below "
        "potential during lockdowns), before closing with the rebound.\n\n"
        "**The end-of-sample trap.** The very latest points are the least reliable: the filter anchors "
        "on recent observations, and the gap there gets heavily revised as new data arrive. Yet it is "
        "precisely the present point that matters for anticipating the next decision. This is the "
        "tool's own limitation, and it should be owned as such.",
    "output_gap_q":
        "The **quarterly** version of the output gap, obtained from a simple HP filter on quarterly "
        "real GDP. It is more responsive than the annual trio, so more useful for anticipating a "
        "quarterly BAM decision.\n\n"
        "**Its movements** track the cycle: a marked dip during Covid (2020), a rebound, then "
        "oscillations around zero across quarters.\n\n"
        "**Its fragility.** Like any HP estimate, it suffers from end-of-sample bias: the last few "
        "quarters get **heavily revised** as new data come in. Use it as a directional signal, never "
        "as an exact measurement.",
    "ipai":
        "The real estate asset price index (base 100 in Q1 2006), published by ANCFCC with Bank "
        "Al-Maghrib. Two curves: overall and residential.\n\n"
        "**The standout fact: stagnation.** Over nearly twenty years, the index has **barely moved in "
        "nominal terms**, oscillating between ~100 and ~114. In other words, adjusted for inflation, "
        "Moroccan property prices have **fallen in real terms**.\n\n"
        "**Neither bubble nor bust.** Unlike many countries, Morocco has seen neither a property boom "
        "nor a crash; the market has stayed remarkably flat, with only mild ripples (a small dip after "
        "2008, stability since).\n\n"
        "**For monetary policy**, the consequence is clear: the housing wealth-effect channel is weak "
        "in Morocco, since real-estate wealth barely appreciates.",
    "m3":
        "Monetary aggregates measure the quantity of money in circulation, ranked by decreasing "
        "liquidity: **M1** (notes and demand deposits), **M2** (M1 plus sight savings) and **M3** (M2 "
        "plus other monetary assets), the broad aggregate most closely watched.\n\n"
        "**Steady growth.** M3 rose from about 700 billion dirhams in the mid-2000s to over **2,000 "
        "billion** today, a steady climb that tracks the expansion of the economy and of credit.\n\n"
        "**Why BAM watches it.** In monetary theory, excessive M3 growth precedes inflation over the "
        "medium term (too much money chasing too few goods). It is therefore a background signal, "
        "best read alongside credit growth.\n\n"
        "**Limitation.** An annual, slow-moving series: useful as structural context, not for fine "
        "decision timing.",
    "capi":
        "The total market capitalisation of the Casablanca Stock Exchange, i.e. the market value of "
        "all listed shares (the MASI index reflects it).\n\n"
        "**What it reflects.** Risk appetite and the valuation of listed companies; in theory it feeds "
        "a wealth-effect channel (when the market rises, holders feel richer and spend more).\n\n"
        "**A narrow market.** The Moroccan listing remains **small and concentrated**: a handful of "
        "sectors (banks, telecoms, real estate) dominate market cap, with limited free float and "
        "modest liquidity.\n\n"
        "**For monetary policy**, this wealth-effect channel therefore plays **less than elsewhere**: "
        "the stock market touches only a small slice of households. Annual data.",
    "depots":
        "The weighted average rate on term deposits (accounts and savings certificates) at 6 and 12 "
        "months, i.e. the **deposit rate** banks pay on locked-in savings. It is the liability mirror "
        "of credit: what a bank pays to fund itself from depositors.\n\n"
        "**What it measures.** The transmission of monetary policy to bank liabilities. When BAM cuts "
        "its key rate, the cost of liquidity falls and banks pay savers less; when it hikes, "
        "competition for deposits pushes these rates up. The reaction is **slow and incomplete**: "
        "banks adjust with a lag and smooth it out, since a term deposit is a multi-month contract.\n\n"
        "**The great rate disinflation (2013-2020).** The dominant feature of the chart is the long "
        "descent. In early 2014, the 12-month rate topped **4%** and the 6-month was close to 3.7%. "
        "BAM cut its key rate from 3% to 2.5% (2014), then 2.25% (2016), and deposit rates followed "
        "step by step: around **3%** in 2016-2017, then below 3% by 2018. Each BAM step shows up in "
        "the slope, with a few months' lag.\n\n"
        "**The Covid shock (2020).** Facing the crisis, BAM cut its key rate to 2% then **1.5%** in "
        "June 2020, a historic low. Term deposit rates slid into the **2% to 2.7%** range, the "
        "decade's floor: locked-in savings barely earned anything in real terms once inflation was "
        "deducted.\n\n"
        "**The anti-inflation tightening (2022-2023), then the easing (2024-2025).** As inflation "
        "surged, BAM raised its key rate from 1.5% to 2% (Sep. 2022), 2.5% (Dec. 2022) then **3%** "
        "(Mar. 2023). The rise in deposit rates was **muted**: the Moroccan banking system was in "
        "relative excess liquidity, so banks had no pressing need to chase deposits and raised payouts "
        "only modestly. Since the 2024-2025 cuts (back toward 2.25%), rates have drifted without a "
        "clear trend around **2.2% to 2.8%**.\n\n"
        "**A reading caution.** These are **weighted averages of the month's new production**: from "
        "one month to the next, the mix of new deposits (large institutional clients vs individuals, "
        "aggressive or passive banks) can swing the figure by dozens of basis points with no monetary "
        "policy move at all. Read the **trend over several months**, not a single point. The 12-month "
        "rate usually sits above the 6-month (a term premium), but the gap is narrow and occasionally "
        "flips.\n\n"
        "**For anticipating BAM**, these rates are a transmission indicator more than a trigger: they "
        "confirm, with a lag, that a past decision has actually spread through the economy. Weak "
        "transmission (rates that barely move after a key-rate move) signals a sluggish bank channel, "
        "which feeds into BAM's diagnosis of how effective its policy is.",
    "debiteurs":
        "Lending rates, i.e. the interest rate banks **charge on new loans**, measured by BAM's "
        "quarterly survey. This is the central link in transmission: monetary policy only bites on the "
        "real economy if a key-rate cut actually feeds through to the cost of credit for businesses "
        "and households.\n\n"
        "**The rate hierarchy.** The chart clearly shows the risk logic. **Consumer** credit is the "
        "most expensive (around **7%**, unsecured, individual borrowers), **equipment** loans the "
        "cheapest (5% to 6%, corporate investment, often collateralised and fiercely competed for "
        "among banks). Cash-flow credit, mortgages and the overall rate sit in between. This ranking "
        "is stable over time.\n\n"
        "**The great easing (2010-2016).** The dominant move is a **steady decline**. The overall rate "
        "starts at **6.49%** in early 2010 and hits a floor around **5.1%** in 2016. This descent "
        "tracks BAM's key-rate cuts over the period: from 3.25% to 3% (2012), 2.75% then 2.5% (2014) "
        "and 2.25% (2016). Transmission works, but is **dampened**: the key rate loses 1 point (from "
        "3.25% to 2.25%) while the overall rate to borrowers falls only about 1.4 point, leaving a "
        "wide bank margin.\n\n"
        "**The mild 2017 rebound.** After the 2016 low, rates edged up gently in 2017 (overall rate at "
        "**5.77%** by year-end) even though the key rate did not move. A sign that credit costs do not "
        "depend on BAM alone: competition, risk perception and liquidity conditions matter too.\n\n"
        "**The Covid floor (2018-2021).** The series kept sliding: from ~5.1% in 2018 down to a low of "
        "around **4.3% to 4.4%** in 2020-2021, as BAM cut its key rate to 2% then **1.5%** (June 2020) "
        "to cushion the pandemic shock. Credit had never been so cheap.\n\n"
        "**The anti-inflation jump (2022-2023).** At end-2022 the overall rate was still at 4.50%, but "
        "as BAM raised its key rate from 1.5% to 2% (Sep. 2022), 2.5% (Dec. 2022) then **3%** (Mar. "
        "2023), lending rates climbed sharply, quarter after quarter: 5.03% in Q1 2023, 5.26% in Q2, "
        "then **5.36%** in Q3-Q4, nearly a **0.9 point** rise in a year. This is the fastest and "
        "cleanest transmission of the whole series, a sign that a tightening passes through faster "
        "than an easing.\n\n"
        "**The recent easing (2024-2026).** As BAM lowers its rate (2.75% in 2024, 2.25% in 2025), the "
        "overall rate eases back to **4.81%** in Q2 2026. **Consumer** credit stays structurally the "
        "most expensive (around 6.8% to 7%), equipment and mortgage loans the cheapest.\n\n"
        "**Why it is decisive for BAM.** These rates directly answer the question the Council asks "
        "itself: is my policy actually reaching the economy? A key-rate cut that fails to lower "
        "lending rates is an **ineffective** policy, and can justify going further. This is also where "
        "credit-supply tensions show up, best read alongside the survey on lending conditions.\n\n"
        "**On construction.** The series stitches together several quarterly BAM releases and now "
        "covers **2010 to 2026 without a break** (66 quarters). It can be used directly in modelling as "
        "a measure of the effective cost of credit and the speed of transmission.",
    "icm":
        "The Household Confidence Index (ICM), published quarterly by the HCP from its national "
        "business-tendency survey. It is a **sentiment index**: the average of household opinion "
        "balances on seven questions (past and expected standard of living, personal finances, "
        "expected unemployment, opportunity to make large purchases).\n\n"
        "**How to read it.** The scale runs from 0 to 200, with **100 as the neutral point**. A "
        "striking fact: across the whole history since 2008, Moroccan ICM **has never reached 100**. "
        "Households are therefore structurally pessimistic; what matters is not the absolute level but "
        "its **direction** and magnitude.\n\n"
        "**The plateau (2008-2019).** For a decade, the index oscillated in a **75 to 87** band, no "
        "strong trend. It even hit the series' high in early 2018 (**87.3**). Sentiment was low in "
        "absolute terms, but stable.\n\n"
        "**The Covid shock (2020).** ICM dropped sharply: from near 78 at end-2019, it fell to around "
        "**65** in Q2 2020, as the lockdown hit employment and incomes.\n\n"
        "**The inflation collapse (2022-2023).** This is the sharpest move on the chart. The surge in "
        "food and energy prices crushed purchasing power, and the index sank to its **all-time low of "
        "44.3** in Q4 2023. Households had never been this gloomy since the measure began.\n\n"
        "**The rebound (2025-2026).** As inflation eased and BAM loosened policy, confidence recovered "
        "markedly: from 54.6 (Q2 2025) it climbed to **64.4** in Q1 2026, before easing to 60.1 in Q2. "
        "A real rebound, but still far below 100.\n\n"
        "**For anticipating BAM.** ICM is a thermometer of **domestic demand**. Depressed confidence "
        "signals soft consumption, hence weak demand-side inflation pressure, which argues for an "
        "accommodative policy; a sharp rebound can instead signal a consumption pickup. It is an "
        "**advance, qualitative** signal: useful to confirm the cycle diagnosis alongside GDP growth "
        "and credit, but too noisy to be a mechanical trigger for a decision.",
    "travail":
        "The Moroccan labour market seen through two rates from the HCP's National Employment Survey "
        "(quarterly, national level): the **unemployment rate** (share of the labour force without a "
        "job) and the **participation rate** (share of the working-age population that is active).\n\n"
        "**A structurally declining participation rate.** This is the most striking fact. The "
        "participation rate has fallen almost without interruption: from **50.9%** in 2006 to about "
        "**44%** in 2025, nearly 7 points lost. In other words, a growing share of working-age "
        "Moroccans are leaving the labour market. Known causes: very low female participation, longer "
        "schooling for young people, and discouragement among some who stop looking for work.\n\n"
        "**An unemployment rate ratcheting upward.** The unemployment rate hovered around 9% to 10% in "
        "the 2010s (a low of 8.5% around 2011), then jumped with Covid: from ~9% in 2019 to **12.3%** "
        "mid-2020, up to a peak near **13.7%**. It has not really come back down since and stays "
        "**stuck above 12%** (12.9% at end-2025). The crisis left a lasting scar.\n\n"
        "**A statistical trap to know.** Unemployment and participation must be read together. A "
        "falling unemployment rate can be good news (job creation) or bad (discouraged people leaving "
        "the labour force, so no longer counted as unemployed). In Morocco, the trend decline in "
        "participation makes the unemployment rate **too optimistic**: it understates true "
        "underemployment. Watch also for **seasonality** tied to agricultural campaigns.\n\n"
        "**For BAM.** BAM's mandate is price stability, not employment (unlike the Fed). But the "
        "labour market informs the diagnosis on the **output gap** and **wage pressure**: high "
        "unemployment and weak participation signal subdued demand and little wage-driven inflation "
        "risk, leaving room to ease.",
    "commerce":
        "External trade in goods: **exports**, **imports** and their **balance** (trade balance), in "
        "billions of dirhams per month. Data from the Office des Changes via the HCP API. This is the "
        "main component of the external accounts, the one that weighs most on the country's financing "
        "needs.\n\n"
        "**A structural trade deficit.** Morocco imports far more than it exports, persistently. Over "
        "the year, imports rose from about **390 billion** in 2014 to over **820 billion** in 2025, "
        "while exports climbed from ~200 to ~470 billion. The balance stays deeply negative and "
        "widens: from about a 190 billion annual deficit in 2014 to over **350 billion** in 2025.\n\n"
        "**What the shocks reveal.** In 2020, Covid crushed both flows and **paradoxically narrowed "
        "the deficit** (imports, energy foremost, fell faster than exports). In 2022, the opposite "
        "shock: the surge in energy and raw material prices blew up the import bill, and the deficit "
        "jumped. Exports, meanwhile, are driven by automotive, phosphates and agri-food, which have "
        "reshaped Morocco's export mix.\n\n"
        "**Scope and limitation.** This balance covers **goods only**. The full balance of payments "
        "adds services (tourism), **remittances from Moroccans abroad** and financial flows (FDI, "
        "debt), which finance a good part of the trade deficit. The goods deficit alone therefore "
        "overstates the true external financing need.\n\n"
        "**For BAM.** The external accounts drive **foreign-exchange reserves** and pressure on the "
        "dirham. A deficit widening too fast strains reserves and can constrain monetary policy "
        "(defending the currency, caution on rate cuts). It is a gauge of external soundness as much "
        "as of activity.",
    "cereales":
        "National cereal output by agricultural season, in millions of quintals (Ministry of "
        "Agriculture via the HCP API): total and by type (soft wheat, durum wheat, barley).\n\n"
        "**Extreme volatility.** This is the chart's signature. From one season to the next, the "
        "harvest can vary threefold: around **105 million quintals** in good years (2017, 2018, 2021) "
        "against **32 to 35 million** in drought years (2020, 2022, 2024). No other series in Data Lab "
        "swings this much.\n\n"
        "**Why it matters for the macro picture.** Agriculture weighs heavily in Moroccan GDP and "
        "employs a large share of the labour force. Since the harvest depends almost entirely on "
        "**rainfall**, a bad cereal season alone can drag down agricultural GDP growth, and therefore "
        "overall GDP, independent of how other sectors are doing. This is why analysts always "
        "distinguish **agricultural GDP** from **non-agricultural GDP**: the latter better reflects "
        "the underlying economic dynamic.\n\n"
        "**The price channel.** A weak harvest does not only hit growth: it tends to **push food "
        "prices** up (less local supply, more wheat imports at world prices), which feeds inflation, "
        "precisely the variable BAM targets.\n\n"
        "**Series limitations.** An **annual and short** series (seasons since 2015-2016), dated to "
        "the harvest year. The **non-cereal** component (market gardening, tree crops, livestock) is "
        "not published separately by this source; the best overall proxy remains agricultural value "
        "added in the national accounts. For anticipating BAM, cereal output mainly serves as an "
        "**early warning** on agricultural GDP and on food prices.",
    "tuc":
        "The capacity utilisation rate (TUC) in industry, from BAM's monthly business survey. It "
        "measures the share of the production apparatus actually in use: a high TUC means factories "
        "run close to full tilt, a low TUC means unused capacity remains.\n\n"
        "**A cruising regime around 73-75%.** Over the 2010s, TUC oscillated with no strong trend "
        "around **74%**, a level reflecting normal operation of Moroccan industry.\n\n"
        "**The Covid air pocket.** The chart's most dramatic move: in **April 2020**, the lockdown "
        "crashed TUC to **46.9%**, unprecedented. Close to half the production apparatus was idle. "
        "The recovery was then very fast, TUC back to its pre-crisis level (~75%) by mid-2021.\n\n"
        "**Tight capacity recently.** After stability around 74% in 2022-2024, TUC climbed toward "
        "**78%** in 2026, a series high. An industry running near its limits can feed price "
        "tensions.\n\n"
        "**For BAM.** TUC is an excellent supply-side proxy for the **output gap** and a monthly "
        "activity signal, far more responsive than quarterly GDP. A high, persistent TUC signals an "
        "economy close to potential, with inflation risk, arguing for caution on rate cuts; a "
        "depressed TUC indicates spare capacity and little pressure, hence room to ease.",
    "conj_ind":
        "Opinion balances from BAM's monthly business-tendency survey (industry, all branches). An "
        "**opinion balance** is the difference between the share of firms reporting an increase and "
        "the share reporting a decrease: above zero, optimists dominate (expansion); below, "
        "pessimists (contraction). Tracked here: production, sales, order books and finished-goods "
        "prices.\n\n"
        "**Production and sales, the pulse of activity.** These two balances move together and drop "
        "sharply in shocks. At the Covid trough (mid-2020), they fell well below **-50**, before "
        "bouncing back firmly into positive territory with the recovery. They remain positive today "
        "(around +30), a sign of expanding activity.\n\n"
        "**Order books, more cautious.** This balance often sits near zero or negative (recently "
        "around -10), reflecting demand judged insufficient, a recurring constraint cited by "
        "industrialists in the survey.\n\n"
        "**Finished-goods prices, an advance inflation signal.** This is the most interesting balance "
        "for BAM. It tracks the inflation cycle: near zero in 2020 (no pressure), it jumped to **+40** "
        "at the mid-2022 inflation peak as manufacturers passed on soaring costs, fell **negative "
        "(-16)** during the 2023 disinflation, then climbed back to around **+29** in 2026. Since it "
        "reflects firms' pricing intentions, it **leads** observed inflation moves.\n\n"
        "**For BAM.** These balances offer a monthly, sector-level read on activity and price "
        "pressure, ahead of official statistics. The price balance in particular is a valuable leading "
        "indicator for the rate decision.",
    "ipp":
        "The producer price index for industry, energy and mining (IPP), published by the HCP on a "
        "base of 100 = 2010, annual, by sector. It measures **factory-gate prices**, i.e. what "
        "producers charge, by major sector (manufacturing, electricity, extractive, water).\n\n"
        "**Why it is useful for BAM.** IPP is an **upstream inflation signal**: when producer costs "
        "and prices rise, they often feed through a few months later into consumer prices (the CPI "
        "BAM targets). It is therefore a leading indicator of the cost channel.\n\n"
        "**What the series shows.** Manufacturing prices rise from about 71 (late 1990s) to **110 in "
        "2021**, electricity climbs faster (up to 122), and the extractive and water sectors are more "
        "jagged. Energy-linked branches (refining, chemicals) are by far the most volatile, tracking "
        "world oil prices.\n\n"
        "**Limitations to know.** **Annual** data on an **old base (2010)**, which **ends in 2021** in "
        "this version of the HCP indicator. It therefore serves as long-run structural context, not a "
        "fine, current signal. For an up-to-date monthly read, the IPP on base 2018 (through 2026) "
        "would be the version to prefer.",
    "ipiem":
        "The industrial, energy and mining production index (IPIEM), published by the HCP on a base "
        "of 100 = 2015. Do not confuse it with IPP: here we measure **volume produced** (quantities), "
        "not prices. It is a barometer of **real industrial activity**, by sector (manufacturing, "
        "electricity, extractive).\n\n"
        "**Manufacturing, the backbone.** The manufacturing index rises steadily, from about **110 to "
        "125** between 2020 and 2025, reflecting a processing industry gaining strength (automotive, "
        "chemicals, agri-food).\n\n"
        "**Electricity, the most dynamic.** Power output climbs markedly, to **nearly 160** in 2025, "
        "driven by demand and renewable capacity. It is the fastest-rising sector over the period.\n\n"
        "**Extractive, a rollercoaster.** This is the most volatile sector: the index peaks around "
        "**148** in 2021 and 2025, but collapses to **90** in early 2023. These swings track the world "
        "**phosphate** cycle (Morocco is a major player): a demand and price surge in 2021-2022, then "
        "a correction in 2023.\n\n"
        "**For BAM.** IPIEM is a direct measure of industrial activity, one of the engines of the "
        "non-agricultural GDP component. Cross-read with TUC and the business-tendency balances, it "
        "helps place the economy in its cycle and gauge the output gap, a key element in the "
        "diagnosis of inflation pressure.\n\n"
        "**On construction.** Series assembled by hand from the HCP's quarterly notes (base 2015), "
        "continuous coverage **Q1 2020 to Q3 2025**. Earlier releases use different bases (2010, 1998) "
        "that cannot be spliced cleanly, hence the 2020 start point.",
    "finances":
        "The Treasury's ordinary revenues and expenditures, in billions of dirhams per year (Ministry "
        "of Finance data, via HCP yearbooks). Ordinary revenues cover taxes (direct, VAT, customs) and "
        "non-tax revenue; ordinary expenditures cover state operating costs, debt service and price "
        "subsidies (compensation).\n\n"
        "**Steady growth on both sides.** Revenues rose from about **147 billion** in 2006 to **409 "
        "billion** in 2025, driven by a broader tax base and nominal growth. Ordinary expenditures "
        "followed, from ~124 to **372 billion**. The last two points (2024-2025) are the actuals "
        "published by the TGR.\n\n"
        "**The scissors open and close depending on the year.** When revenues grow faster than "
        "spending, the ordinary balance improves; the reverse widens the financing need. The "
        "**compensation** subsidy line was for a long time the main destabiliser, before its gradual "
        "reform from 2013.\n\n"
        "**For BAM.** Fiscal policy is the complement to monetary policy. Very expansive public "
        "spending can fuel demand and inflation, complicating BAM's task; a consolidating budget works "
        "in the same direction as a tightening. Revenues are also a good thermometer of underlying "
        "economic activity.",
    "deficit":
        "The Treasury's overall budget deficit and debt service (interest paid), in billions of "
        "dirhams per year. The **overall deficit** is computed after investment spending and special "
        "accounts: it is therefore not simply ordinary revenues minus ordinary expenditures, and it "
        "measures the state's true **borrowing need**.\n\n"
        "**Near-balance before the crisis (2007-2008).** Morocco even posted small surpluses (around "
        "+3 to +4 billion), thanks to buoyant tax revenue and privatisations.\n\n"
        "**The slippage (2009-2012).** The global crisis, and above all the explosion of "
        "**compensation** spending (subsidised oil prices soaring), widened the deficit to a low of "
        "**-57.6 billion in 2012**. This slippage is what triggered the subsidy reform.\n\n"
        "**Consolidation (2013-2019).** The deficit gradually narrowed toward **-41 billion**, helped "
        "by de-subsidisation and firmer revenue.\n\n"
        "**The Covid shock (2020).** The deficit blew out to **-82.3 billion**, a record, driven by "
        "falling revenue and crisis spending. It then narrowed and stabilised around **-61.5 billion** "
        "in 2024 and 2025 (TGR actuals).\n\n"
        "**Debt service**, meanwhile, has climbed steadily (from ~19 billion in 2006 to **43 billion** "
        "in 2025), reflecting a growing debt stock and rising rates. For BAM, a wide deficit and "
        "expensive debt weigh on long rates and on the room for manoeuvre of economic policy.",
    "directeur":
        "Bank Al-Maghrib's key rate, i.e. the rate at which it refinances banks. This is the "
        "instrument of monetary policy, and therefore the variable this project tries to anticipate: "
        "at every quarterly Council meeting, BAM decides to raise it, cut it, or leave it unchanged. "
        "Reconstructed here as a step series from the official decision history.\n\n"
        "**The long plateau (2006-2011).** The rate stayed at **3.25%** for five years, with a single "
        "round trip (a hike to 3.50% in summer 2008 against pre-crisis inflation, back to 3.25% in "
        "early 2009). BAM moves rarely, and in small steps.\n\n"
        "**The long easing (2012-2016).** A gradual decline: 3.00% in 2012, then 2.75% and 2.50% in "
        "2014, finally **2.25%** in 2016, a floor that would hold for four years. Low inflation and "
        "soft growth justified an accommodative bias.\n\n"
        "**The Covid shock (2020).** Two rapid cuts, to 2.00% in March then **1.50%** in June 2020, a "
        "historic low to support the locked-down economy.\n\n"
        "**The anti-inflation tightening (2022-2023).** Facing the price surge, BAM raised the rate "
        "from 1.50% to 2.00% (Sep. 2022), 2.50% (Dec. 2022) then **3.00%** (Mar. 2023), three "
        "consecutive hikes, the fastest cycle in the series.\n\n"
        "**The recent easing (2024).** Once inflation eased, three cuts brought the rate back to "
        "**2.25%** by end-2024, a level held since.\n\n"
        "**What this means for the model.** Out of about **80 meetings since 2006, only ~14 produced "
        "a move** (4 hikes, 10 cuts); everything else was the status quo. The target is therefore "
        "heavily imbalanced: predicting \"status quo\" is correct most of the time, and the real "
        "difficulty is anticipating the rare moments when BAM moves. Compare any series to this curve "
        "(via the \"Compare\" tool and the correlation reading) to spot the inputs that best track the "
        "decisions.",
}
